spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          # search-locations: "file:///D:/micro_ws/configserver/src/main/resources/config"
          # search-locations: "file:///Users//mybank//Documents//config"
        git:
          uri: "https://github.com/atmurisaritha99/mybank.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F1"
server:
  port: 8071